### ISSUE TITLE
Sometimes blank panels are generated from command-line vplot

### ISSUE THREAD

**Issue by RoryBarnes** [VirtualPlanetaryLaboratory/vplot#3] opened 2018-10-03 19:15 UTC
In some cases, the executable generates more panels than output variables and prints the message "No handles with labels found to put in legend." See https://github.com/RoryBarnes/40Eri for an example.

**Comment by rodluger** [comment] 2018-10-05 13:23
The issue is that in `saOutputOrder` you specified `Age` for the star instead of `Time`. The default  x axis parameter is `Time`, which you can change to `Age` by running
```
vplot -x Age
```
But that won't fix your issue, because for the planet you specified `Time`. Currently `vplot` only supports a single independent variable for plotting. We could think about changing this, but I think the easiest fix for you is to change `Age` to `Time` in the star's `saOutputOrder`.

**Comment by rodluger** [comment] 2019-12-01 18:45
I'm now requiring that there exist a `Time` array in at least one of the input files for the auto plotting to work in vplot.

**Closed as completed by rodluger** 2019-12-01 18:45 UTC
